### ISSUE TITLE
Docs link 404s

### ISSUE THREAD

**Issue by toebeann** [tsdotnet/promises#1]
Navigating to https://tsdotnet.github.io/promises/ results in a 404 error

**Comment by electricessence** [comment]
Will look into it.  Typedoc has given me trouble in the past.  Thanks for reporting it.

**Comment by electricessence** [comment]
Wasn't enabled in the repo.  It is now.  But looks like the docs still need updating.

**Comment by electricessence** [comment]
Renamed all the urls since they were case sensitive.  Looks good now.
